baseurl = "https://www.easterinrva.com"
languageCode = "en-us"
title = "Easter in RVA"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]
	name = "Easter in RVA"
	description = "At Hill City, our mission is to be a safe place for you to explore your faith. We'd be honored to have you during one of our Easter services this year!"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Easter In RVA"

		[params.navigation.links]
			register = "Join Us"
			info = "Let Us Know"
			expect = "What to Expect"
			contest = "Best Day in RVA"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan = " "


	# Registration section
	[params.register]
		headline     = "Come join us!"
		description1 = "Friday, March 30th: Good Friday / 6:00 & 7:30PM"
		description2 = "Sunday, April 1st: Easter Sunday / 8:00, 9:30 & 11:00AM"
		address = "2101 Maywill St, Richmond VA 23230"

	[params.info]
		headline = "The greatest story of freedom and hope is the one we celebrate on Easter Sunday."

	[params.expect]
		headline = "What to Expect"
		description1 = "If this is your first time to Hill City, or your first time in a while, we’re so excited to see you!"
		description2 = "Our services last for about 60 minutes, and the doors to our auditorium will open about 30 minutes beforehand. You can dress however you like! Your fancy Easter bonnet, or jeans and a t-shirt are fine by us."
		description3 = "Once you arrive, our team will help you find a parking spot and guide you in the right direction. If you have kids, we’ll direct you to our kids check-in where we have full Easter experiences for Infant-Elementary. Your morning cup of coffee is on us, too!"
		sermonsLink = "http://hillcityrva.com/sermons"

	# Footer section
	[params.footer]
		services	= "Sundays:<br>8:30, 9:45, 11:00 AM, 4:00 PM"
		location	= "Hill City Church <br> 2101 Maywill St.<br>Richmond, VA 23230"
		address		= "P.O. Box 18160<br>Richmond, VA 23226"
 
		[params.footer.socialMedia]
			facebook  = "https://www.facebook.com/hillcityrva/"
			instagram = "https://www.instagram.com/hillcityrva/?hl=en"